import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

const Home: NextPage = () => {
  const [canvas, setCanvas] = useState<number[][]>([
    [0, 0, 0, 0],
    [0, 2, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 2, 0],
  ]);
  return (
    <div>
      <Head>
        <title>2048 GAME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h1 className="title">2048 GAME</h1>
        <div className="canvas">
          {canvas.map((row) => {
            return row.map((field, index) => {
              return (
                <div key={index} className="grid-box">
                  {field === 2 && <img src="../assets/svg/2.svg" />}
                </div>
              );
            });
          })}
        </div>
      </div>
    </div>
  );
};

export default Home;
